### ISSUE TITLE
作者可以留一个赞赏二维码吗？

### ISSUE THREAD

**Issue by yxzlwz** [xiaobinxxx/996Shopping#2]
大爱这个项目！在帮学校做一个二手交易平台，这套模板几乎涵盖了所有我需要的界面，甚至远远超出我的预期！代码结构也很易读。

如果作者能看到的话希望可以留下一个赞赏二维码，本人学生可能无法给予太多支持，但一定努力表示自己的感谢。

**Comment by xiaobinxxx** [comment]
不需要的哈，能够帮到你就好，多多努力，加油!

**Comment by yxzlwz** [comment]
Thx
